---
- name: install packages
  become: yes 
  yum: 
    pkg: 
      - curl
      - git
      - ctags
      - cmake
      - screen
      - python-devel
      - devtoolset-6
      - centos-release-scl
    state: installed

- name: enable devtoolset-6 for ycm
  shell: "scl enable devtoolset-6 bash"

- name: copy vimrc 
  copy:
    src: .vimrc
    dest: ~/.vimrc

- name: create plugin dirs
  file: 
    path:
      - ~/.vim/autoload
      - ~/.vim/bundle
      - ~/ycm_build 
    state: directory

- name: copy pathogen.vim
  copy:
    src: pathogen.vim
    dest: ~/.vim/autoload

- name: install vi plugins
  git:
    repo: "https://github.com/{{item.name}}/{{item.dest}}.git"
    dest: "~/.vim/bundle/{{item.dest}}"
  with_items: 
  - { name: "junegunn", dest: "fzf" }
  - { name: "majutsushi", dest: "tagbar" }
  - { name: "scrooloose", dest: "nerdtree" }
  - { name: "Raimondi", dest: "delimitMate" }
  - { name: "vim-syntastic", dest: "syntastic" }
  - { name: "vim-airline", dest: "vim-airline" }
  - { name: "Valloric", dest: "YouCompleteMe" }

- name: update vi to 8
  yum:
    pkg: vim
    state: latest

- name: setup youCompleteMe
  script: ycm.sh

- name: get plugins 
  shell: ls ~/.vim/bundle
  register: plugins

- debug: 
    var: plugins.stdout_lines
...
