---
- name: install packages
  become: yes 
  yum: 
    pkg: 
      - curl
      - git
      - ctags
      - cmake
      - screen
      - python-devel
      - centos-release-scl-rh
      - devtoolset-6
    state: installed

- name: install devtoolset-6
  become: yes
  yum:
    pkg: devtoolset-6
    state: installed

- name: copy vimrc 
  copy:
    src: .vimrc
    dest: ~/.vimrc

- name: create plugin dirs
  file: 
    path: "{{item}}"
    state: directory
  with_items:
  - ~/.vim/autoload
  - ~/.vim/bundle
  - ~/ycm_build 

- name: copy pathogen.vim
  copy:
    src: pathogen.vim
    dest: ~/.vim/autoload

- name: install vi plugins
  git:
    repo: "https://github.com/{{item.name}}/{{item.dest}}.git"
    dest: "~/.vim/bundle/{{item.dest}}"
  with_items: 
  - { name: "junegunn", dest: "fzf" }
  - { name: "majutsushi", dest: "tagbar" }
  - { name: "scrooloose", dest: "nerdtree" }
  - { name: "Raimondi", dest: "delimitMate" }
  - { name: "vim-syntastic", dest: "syntastic" }
  - { name: "vim-airline", dest: "vim-airline" }
  - { name: "Valloric", dest: "YouCompleteMe" }

- name: update vi to 8
  script: getVim8.sh

- name: start ycm setup
  script: ycm.sh 

- name: get plugins 
  shell: ls ~/.vim/bundle
  register: plugins

- debug: 
    var: plugins.stdout_lines
...
