---
- name: install packages
  become: yes
  yum:
    pkg:
      - gcc-c++
      - cmake
      - make
      - python3
      - python3-devel
      - mono-complete
      - golang
      - vim
      - git
      - curl
      - npm
      - node
      - nodejs
      - ctags
      - screen
      - yamllint
    state: installed

- name: copy vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc

- name: create plugin dirs
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle
    - ~/ycm_build

- name: copy pathogen.vim
  copy:
    src: pathogen.vim
    dest: ~/.vim/autoload

- name: install vi plugins
  git:
    repo: "https://github.com/{{item.name}}/{{item.dest}}.git"
    dest: "~/.vim/bundle/{{item.dest}}"
  with_items:
    - {name: "junegunn", dest: "fzf"}
    - {name: "majutsushi", dest: "tagbar"}
    - {name: "ternjs", dest: "tern_for_vim"}
    - {name: "scrooloose", dest: "nerdtree"}
    - {name: "Raimondi", dest: "delimitMate"}
    - {name: "Valloric", dest: "YouCompleteMe"}
    - {name: "vim-syntastic", dest: "syntastic"}
    - {name: "vim-airline", dest: "vim-airline"}
    - {name: "python-mode", dest: "python-mode"}
    - {name: "rafi", dest: "awesome-vim-colorschemes"}


- name: start ycm setup
  shell: >
   python3 ~/.vim/bundle/YouCompleteMe/install.py --all

- name: start ternjs setup
  shell: >
    cd ~/.vim/bundle/tern_for_vim;
    npm install

- name: start python-mode setup
  shell: >
    cd ~/.vim/bundle/python-mode;
    git submodule update --init --recursive

- name: get plugins
  shell: ls ~/.vim/bundle
  register: plugins

- debug:
    var: plugins.stdout_lines
